apiVersion: v1
kind: Secret
metadata:
  name: travel-planner-secrets
type: Opaque
stringData:
  groq-api-key: "YOUR_GROQ_API_KEY"
  tavily-api-key: "YOUR_TAVILY_API_KEY"
  openweather-api-key: "YOUR_OPENWEATHER_API_KEY"
  aviation-stack-api-key: "YOUR_AVIATION_STACK_API_KEY"
